# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0002_karyawan_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='foto',
            field=models.ImageField(blank=True, upload_to='upload/'),
        ),
    ]
