# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kehadiran', '0002_auto_20160819_1054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Izin',
            new_name='Izin2',
        ),
    ]
